version: '3.9'

volumes:
  metrics:

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # Receive legacy OpenTracing traces, optional
      - "4317:4317"    # OTLP gRPC receiver
      - "4318:4318"    # OTLP HTTP receiver, not yet used by Quarkus, optional
      - "14250:14250"  # Receive from external otel-collector, optional

  postgres_local:
    image: postgres:latest
    container_name: postgres_local
    environment:
      - POSTGRES_USER=nicolas
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=local
    ports:
      - "5432:5432"

  prometheus:
    image: bitnami/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - metrics:/etc/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
